version: "3.8"

# ==============================================================================
# ANCHORS
# ==============================================================================

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

# ==============================================================================
# SERVICES
# ==============================================================================

services:

  gitlab-clone:
    container_name: ${CONTAINER_NAME}
    env_file: [ "./.env" ]
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: on-failure
    logging: *default-logging
